name: "yolo11s"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, -1, -1 ]   # (C, H, W) — Triton добавит batch
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 84, -1 ]      # <- важно: без батч-оси. Triton добавит её -> [-1,84,-1]
  }
]

instance_group [
  { kind: KIND_CPU count: 1 }
]

dynamic_batching {
  preferred_batch_size: [ 4, 8 ]
  max_queue_delay_microseconds: 1000
}
