# Main configuration file
defaults:
  - data: default
  - model: yolo_efficientnet
  - train: default
  - inference: default
  - export: default
  - _self_

# MLflow settings
mlflow:
  tracking_uri: "http://127.0.0.1:8080"
  experiment_name: "steel_defect_detection"

# Paths
paths:
  data_dir: "data"
  models_dir: "models"
  logs_dir: "logs"
  plots_dir: "plots"

# General settings
seed: 42
device: "cuda" # or "cpu"
